### ISSUE TITLE
Hash rápido - Agregar al Team Reference

### ISSUE THREAD

**Issue by ajfabian** [Saborit10/3N1M4-Team-Reference#3]
Considero que la implementación de un hash rápido puede ser agregada al Team Reference.
Si no existe la necesidad de preguntar por el hash de varios rangos de una "cadena", se puede obviar el módulo y aprovechar el overflow de los enteros de C++, lo que mejora significativamente la velocidad del código.
No módulear  - > código más rápido.
Esto se logra usando la versión `unsigned` de `int` o `long long` y operando como usualmente, esto creará un moduleo por defecto. Y a cadenas iguales le seguiran correspondiendo valores hash iguales.

**Comment by Saborit10** [comment]
Se ha agregado un codigo para implementar un hash rapido. Esta pendiente de testing.
